name: HubCore
version: 1.0.0
main: net.cengiz1.hubcore.HubCore
api-version: 1.21
authors: [Cengiz1]
description: A comprehensive hub/lobby management system
depend: [ProtocolLib]

commands:
  lobby:
    description: Teleport to a lobby
    usage: /lobby [id]
    aliases: [l]

  setlobby:
    description: Set a lobby spawn point
    usage: /setlobby [id]
    permission: multihub.setlobby

  hub:
    description: Teleport to the main hub
    usage: /hub
    aliases: [h]

  spawn:
    description: Teleport to the current lobby spawn
    usage: /spawn
    aliases: [s]

  multihubreload:
    description: Reload the HubCore plugin
    usage: /multihubreload
    permission: hubcore.reload
    aliases: [hreload]

  chatlock:
    description: Lock or unlock the server chat
    usage: /chatlock
    permission: hubcore.chatlock

  announce:
    description: Send an announcement to all players
    usage: /announce <message> or /announce next
    permission: hubcore.announce

  npc:
    description: Manage server NPCs
    usage: /npc help
    permission: hubcore.npc

permissions:
  hubcore.reload:
    description: Allows reloading the plugin configuration
    default: op

  hubcore.chatlock:
    description: Allows locking/unlocking the server chat
    default: op

  hubcore.announce:
    description: Allows sending announcements to all players
    default: op

  hubcore.npc:
    description: Allows managing server NPCs
    default: op