name: LuneHubCore
version: 1.0.0
main: net.cengiz1.lunehubcore.LuneHubCore
api-version: 1.13
authors: [cengiz1]
description: Gelişmiş hub sistemi
commands:
  lobby:
    description: Ana lobiye ışınlanın
    aliases: [l]
  setlobby:
    description: Lobi spawn noktasını ayarlayın
  hub:
    description: Ana lobiye ışınlanın
    aliases: [h]
  spawn:
    description: Bulunduğunuz lobinin spawn noktasına ışınlanın
    aliases: [s]
  multihubreload:
    description: Eklenti yapılandırmasını yeniden yükleyin
    aliases: [lunehubreload, hubreload]
  chatlock:
    description: Sohbeti kilitle veya kilidini aç
    aliases: [cl, lockChat, chatl]
    usage: /chatlock
permissions:
  lunehub.build:
    description: Blok kırma ve yerleştirme izni
    default: op
  lunehub.admin:
    description: Tüm LuneHub komutlarını kullanma izni
    default: op
    children:
      lunehub.build: true
      lunehub.setlobby: true
      lunehub.reload: true
      lunehub.chatlock: true
  lunehub.setlobby:
    description: Lobi spawn noktasını ayarlama izni
    default: op
  lunehub.reload:
    description: Eklentiyi yeniden yükleme izni
    default: op
  lunehub.chatlock:
    description: Sohbeti kilitleme ve açma izni
    default: op
  lunehub.chatbypass:
    description: Sohbet kilitliyken bile konuşabilme izni
    default: op
  lunehub.interact:
    description: Düğme, kapı vb. ile etkileşimde bulunma izni
    default: op
  lunehub.dropitem:
    description: Eşya atma izni
    default: op